import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";

async function imageFromChunks(paths){
  const parts=await Promise.all(paths.map(async p=>{const r=await fetch(p,{cache:"force-cache"});if(!r.ok)throw new Error(`Missing asset ${p}`);return (await r.text()).trim()}));
  const raw=atob(parts.join(""));const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
  return URL.createObjectURL(new Blob([bytes],{type:"image/avif"}));
}

const [cosmosAsset,worldAsset,hearthAsset]=await Promise.all([
  imageFromChunks(["/assets/generated/cosmic-00.b64","/assets/generated/cosmic-01.b64","/assets/generated/cosmic-02.b64","/assets/generated/cosmic-03.b64"]),
  imageFromChunks(["/assets/generated/world-live-00.b64","/assets/generated/world-live-01.b64","/assets/generated/world-live-02.b64"]),
  imageFromChunks(["/assets/generated/hearth-live-00.b64","/assets/generated/hearth-live-01.b64","/assets/generated/hearth-live-02.b64"])
]);

const territories=[
  {id:"hearthlands",name:"The Hearthlands",lat:25,lon:0,interactive:true,cues:["homes","gardens","warm light","family","belonging"]},
  {id:"roadlands",name:"The Roadlands",lat:15,lon:36,cues:["roads","journeys","movement","crossings"]},
  {id:"institutional",name:"Institutional Quarter",lat:58,lon:68,cues:["formal buildings","systems","authority","public space"]},
  {id:"littoral",name:"Littoral Coast",lat:-29,lon:119,cues:["coast","islands","shorelines","sea"]},
  {id:"river",name:"River Country",lat:15,lon:-79,cues:["rivers","bridges","waterways","flow"]}
];
const places=[
  {name:"Family Home",x:12,y:58,kind:"place"},{name:"Cambridge Road Childhood House",x:29,y:47,kind:"place"},{name:"Current / Present House",x:45,y:61,kind:"place"},{name:"The Large Many-Roomed House",x:62,y:19,kind:"place"},{name:"The Unfamiliar House",x:83,y:45,kind:"place"},{name:"Fox",x:8,y:78,kind:"symbol"}
];

const app=document.querySelector("#app");
app.innerHTML=`<main class="atlas" data-state="orbit" data-layer="places">
<div class="cosmic-art"><img src="${cosmosAsset}" alt=""></div><canvas id="starscape" class="starscape"></canvas><div class="cosmic-veil"></div>
<header class="topbar"><div class="brand"><span class="sigil">✦</span><div><b>DREAMSCAPE</b><small>DREAM ATLAS</small></div></div><nav class="mainnav"><a class="active">World</a><a>Journal</a><a>Insights</a><a>Collections</a></nav><div class="stats"><span>✶ 213 dreams</span><span>☾ 5 mapped places</span></div></header>
<aside class="left-poem"><p>A world<br>shaped by your<br>dreams.</p><small>Explore<br>remember<br>belong</small></aside>
<div class="globe-stage"><canvas id="globe"></canvas><div class="territory-labels"></div><div class="orbit-help">Drag to rotate · select the glowing Hearthlands</div><div class="bottom-quote">“The same world, again and again,<br>but always new.”</div></div>
<aside class="focus-panel"><button class="close-focus">×</button><p class="roman">I · THE DOMESTIC HEART</p><h1>The Hearthlands</h1><p class="subtitle">Where belonging keeps changing shape</p><div class="rule"></div><p class="body">A warm domestic territory formed from recurring homes, gardens, family settings, firelight, memory and belonging across the dream corpus.</p><div class="focus-meta"><span><b>213</b>dreams here</span><span><b>5</b>mapped places</span><span><b>37</b>recurring symbols</span></div><div class="theme-pills"><span>Home</span><span>Family</span><span>Gardens</span><span>Warm light</span><span>Fox</span></div><button class="enter">Travel into The Hearthlands <span>→</span></button></aside>
<div class="descent-copy"><span>TRAVELLING INTO</span><b>THE HEARTHLANDS</b></div>
<section class="flatmap-scene"><div class="flatmap-world"><img class="flatmap-art" src="${hearthAsset}" alt="The Hearthlands"><div class="flatmap-wash"></div><div class="flatmap-markers"></div></div><header class="hearth-bar"><button class="return-world">← Return to the world</button><div class="hearth-heading"><b>The Hearthlands</b><small>213 dreams</small></div><div class="layer-switch"><button data-show="places" class="active">Places</button><button data-show="symbols">Symbols</button></div></header><div class="arrival-whisper"><span>THE HEARTHLANDS</span><b>Homes, gardens, paths and warm lights gather into one remembered landscape.</b></div></section>
<aside class="place-sheet"><button class="close-place">×</button><p class="roman">THE HEARTHLANDS</p><h2>Family Home</h2><p>A named recurring place from the Hearthlands corpus. Its source-dream evidence remains a separate reading layer.</p></aside><div class="vignette"></div></main>`;

const root=document.querySelector(".atlas"),canvas=document.querySelector("#globe"),labels=document.querySelector(".territory-labels"),flatmap=document.querySelector(".flatmap-scene"),mapWorld=document.querySelector(".flatmap-world"),markerLayer=document.querySelector(".flatmap-markers"),placeSheet=document.querySelector(".place-sheet");
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.z=3.05;const group=new THREE.Group();scene.add(group);
const tex=new THREE.TextureLoader().load(worldAsset);tex.colorSpace=THREE.SRGBColorSpace;tex.wrapS=THREE.RepeatWrapping;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();
const globe=new THREE.Mesh(new THREE.SphereGeometry(1,180,140),new THREE.MeshStandardMaterial({map:tex,roughness:.96,metalness:.01}));group.add(globe);
scene.add(new THREE.HemisphereLight(0xd8e4ff,0x1b1020,2.5));const sun=new THREE.DirectionalLight(0xffdfbd,2.65);sun.position.set(-3.8,2.6,4.8);scene.add(sun);const fill=new THREE.DirectionalLight(0x8fa7ff,.8);fill.position.set(3,-1,2.5);scene.add(fill);
// Intentionally no RingGeometry and no atmosphere shell.
function vec(lat,lon,r=1.025){const phi=(90-lat)*Math.PI/180,theta=(lon+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta))}
const markerItems=[];for(const t of territories){const p=vec(t.lat,t.lon);const dot=new THREE.Mesh(new THREE.SphereGeometry(t.interactive?.028:.016,18,18),new THREE.MeshBasicMaterial({color:t.interactive?0xffb45e:0xf1d8a7}));dot.position.copy(p);group.add(dot);let hit=null;if(t.interactive){hit=new THREE.Mesh(new THREE.SphereGeometry(.09,16,16),new THREE.MeshBasicMaterial({transparent:true,opacity:0}));hit.position.copy(p);group.add(hit)}const el=document.createElement("button");el.className=`territory-label ${t.interactive?"primary":""}`;el.innerHTML=`<i></i><span>${t.name}</span>`;el.title=t.cues.join(" · ");if(t.interactive)el.onclick=()=>focus();labels.appendChild(el);markerItems.push({t,dot,hit,el})}
let state="orbit",rx=-.08,ry=-Math.PI/2,zoom=3.05,drag=false,sx=0,sy=0,px=0,py=0,vx=0,vy=0,descentStart=0;const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
function worldPos(item){return item.dot.getWorldPosition(new THREE.Vector3())}function screen(p){const q=p.clone().project(camera);return{x:(q.x*.5+.5)*innerWidth,y:(-q.y*.5+.5)*innerHeight}}function visible(p){return p.clone().normalize().dot(camera.position.clone().sub(p).normalize())>.03}
function updateLabels(now){for(const m of markerItems){const p=worldPos(m),s=screen(p),show=visible(p)&&state!=="hearth";m.el.style.left=`${s.x}px`;m.el.style.top=`${s.y}px`;m.el.style.opacity=show?1:0;m.el.style.pointerEvents=show&&state==="orbit"&&m.t.interactive?"auto":"none";if(m.t.interactive)m.dot.scale.setScalar(.88+Math.sin(now*.004)*.16)}}
function focus(){if(state!=="orbit")return;state="focus";root.dataset.state="focus"}
function descend(){if(state!=="focus")return;state="descent";root.dataset.state="descent";descentStart=performance.now()}
function back(){state="orbit";root.dataset.state="orbit";rx=-.08;ry=-Math.PI/2;zoom=3.05;camera.position.z=zoom;camera.fov=34;camera.updateProjectionMatrix();flatmap.style.opacity=0;flatmap.style.clipPath="circle(0% at 50% 50%)";placeSheet.classList.remove("open")}
document.querySelector(".enter").onclick=descend;document.querySelector(".close-focus").onclick=()=>{state="orbit";root.dataset.state="orbit"};document.querySelector(".return-world").onclick=back;document.querySelector(".close-place").onclick=()=>placeSheet.classList.remove("open");
canvas.onpointerdown=e=>{if(state!=="orbit")return;drag=true;sx=px=e.clientX;sy=py=e.clientY;canvas.setPointerCapture(e.pointerId);root.classList.add("dragging")};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-sx,dy=e.clientY-sy;ry+=dx*.0042;rx=THREE.MathUtils.clamp(rx+dy*.0042,-.68,.68);vx=dy*.001;vy=dx*.001;sx=e.clientX;sy=e.clientY};canvas.onpointerup=e=>{if(!drag)return;drag=false;root.classList.remove("dragging");if(Math.hypot(e.clientX-px,e.clientY-py)>8)return;const r=canvas.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const h=markerItems.find(m=>m.t.id==="hearthlands");if(ray.intersectObjects([h.hit,h.dot]).length)focus()};canvas.onwheel=e=>{if(state!=="orbit")return;e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.0013,2.15,4.05)};
for(const p of places){const b=document.createElement("button");b.className=`map-marker ${p.kind}`;b.style.left=`${p.x}%`;b.style.top=`${p.y}%`;b.innerHTML=`<i></i><span>${p.name}</span>`;b.onclick=()=>{placeSheet.querySelector("h2").textContent=p.name;placeSheet.classList.add("open")};markerLayer.appendChild(b)}document.querySelectorAll(".layer-switch button").forEach(b=>b.onclick=()=>{root.dataset.layer=b.dataset.show;document.querySelectorAll(".layer-switch button").forEach(x=>x.classList.toggle("active",x===b))});
const starCanvas=document.querySelector("#starscape"),ctx=starCanvas.getContext("2d");let stars=[];function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();const d=Math.min(devicePixelRatio||1,2);starCanvas.width=innerWidth*d;starCanvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(650,Math.max(260,Math.round(innerWidth*innerHeight/4200)))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.2+Math.random()*1.5,a:.15+Math.random()*.65,p:Math.random()*6.28}))}addEventListener("resize",resize);resize();
function drawStars(t){ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){const q=.72+Math.sin(t*.001+s.p)*.28;ctx.fillStyle=`rgba(255,244,218,${s.a*q})`;ctx.beginPath();ctx.arc(s.x,s.y,Math.max(.1,s.r*q),0,Math.PI*2);ctx.fill()}}
function animate(now){drawStars(now);if(state==="orbit"){if(!drag){rx+=vx;ry+=vy;vx*=.93;vy*=.93;ry+=.00045}camera.position.z+=(zoom-camera.position.z)*.08}else if(state==="focus"){rx+=(-.08-rx)*.08;ry+=(-Math.PI/2-ry)*.08;camera.position.z+=(2.5-camera.position.z)*.09}else if(state==="descent"){const p=Math.min(1,(now-descentStart)/3600),e=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;rx+=(-.08-rx)*.12;ry+=(-Math.PI/2-ry)*.12;camera.position.z=THREE.MathUtils.lerp(2.5,1.02,e);camera.fov=THREE.MathUtils.lerp(34,54,e);camera.updateProjectionMatrix();const reveal=Math.max(0,(p-.32)/.68);flatmap.style.opacity=Math.min(1,reveal*1.2);flatmap.style.clipPath=`circle(${reveal*150}% at 50% 50%)`;if(p>=1){state="hearth";root.dataset.state="hearth";flatmap.style.opacity=1;flatmap.style.clipPath="circle(150% at 50% 50%)"}}group.rotation.set(rx,ry,0);renderer.render(scene,camera);updateLabels(now);requestAnimationFrame(animate)}requestAnimationFrame(animate);
