const root=document.querySelector("#app");
const bp=await (await fetch("/worlds/natalie-world.json",{cache:"no-store"})).json();
const art={luminous:"/assets/worlds/natalie/luminous.svg","direct-message":"/assets/worlds/natalie/direct-message.svg",otherworldly:"/assets/worlds/natalie/otherworldly-world.svg",threshold:"/assets/worlds/natalie/threshold.svg",integration:"/assets/worlds/natalie/integration.svg",shadow:"/assets/worlds/natalie/shadow.svg"};
const short={luminous:"Awe, revelation and sacred beauty","direct-message":"Clarity, guidance and knowing",otherworldly:"Impossible reality and strange wonder",threshold:"Journeys, crossings and states of transition",integration:"Restoration, renewal and embodied wholeness",shadow:"Confinement, intensity and the possibility of emergence"};
const glyph={Train:"⌁",Bridge:"⌒",Bus:"◇",Road:"↝",Motorhome:"⌂",Home:"⌂",Bee:"✣",Water:"≋",Spa:"◌",Cleansing:"✧",Dance:"⌁",Body:"◯",Tower:"♜",Labyrinth:"⌘",Passage:"⋄",Smoke:"〰",Ruins:"⌑",Escape:"↗",Portal:"◉","Floating Land":"◒","Strange Structure":"⌬","Double Dream":"◐",Sky:"☾",Fragment:"◆",Mountain:"△",Moon:"☽",Aurora:"⌇",Alignment:"✶","Golden Cloud":"☁",Ray:"✦",Message:"✧",Temple:"⌂",Library:"▤",Inscription:"≡",Path:"⌁",Knowing:"◉"};
root.innerHTML='<main class="living-cosmos"><div class="cosmos-bg"><div class="nebula n1"></div><div class="nebula n2"></div><div class="nebula n3"></div><canvas class="star-canvas"></canvas><div class="cosmic-glow"></div></div><button class="back">← Sam’s Dreamscape</button><header class="hero"><div class="kicker">DREAMSCAPE · A WORLD MADE FROM DREAMS</div><h1>NATALIE’S DREAMSCAPE</h1><p>SIX DREAM TERRITORIES CRYSTALLISED INTO ONE LIVING COSMOS</p></header><div class="prototype">Prototype corpus sample · final counts pending</div><section class="world-grid"></section><div class="hint">✦ Hover a world · click to enter its constellation</div><section class="focus-layer"><button class="focus-close">×</button><div class="focus-world-wrap"><div class="focus-world"></div><div class="focus-caption"><small>PROVISIONAL WORLD</small><h2></h2><p></p></div></div><div class="tarot-ring"></div><button class="enter-world">Enter World <span>→</span></button></section><section class="flatmap-layer"><button class="flat-close">×</button><div class="flat-header"><small>ENTERING TERRITORY</small><h2></h2><p></p></div><div class="flatmap-art"></div><div class="flat-symbols"></div><div class="flat-note">Experimental flat-map bridge · symbols and Tarot remain corpus-driven.</div></section><aside class="tarot-reader"><button class="tarot-close">×</button><div class="ornament">☾ ✦ ☽</div><small>DREAMSCAPE TAROT · PROVISIONAL SYMBOL</small><h3></h3><div class="rule"></div><p></p></aside></main>';
const shell=document.querySelector(".living-cosmos"),grid=document.querySelector(".world-grid"),focus=document.querySelector(".focus-layer"),flat=document.querySelector(".flatmap-layer"),reader=document.querySelector(".tarot-reader");
let selected=null;
bp.worlds.forEach(function(w){var c=document.createElement("button");c.className="world-card world-"+w.id;c.innerHTML='<div class="world-orb"><img class="world-base" src="'+art[w.id]+'" alt=""><div class="clouds c1"></div><div class="clouds c2"></div><div class="water-shimmer"></div><div class="lights"></div><div class="mist"></div><div class="portal"></div><div class="aurora"></div><div class="embers"></div><div class="route-light"></div><div class="bee bee1">✦</div><div class="bee bee2">✦</div></div><div class="world-label"><b>'+w.label+'</b><span>'+short[w.id]+'</span></div>';c.onclick=function(){openWorld(w)};grid.appendChild(c)});
function openWorld(w){selected=w;shell.classList.add("is-focus");focus.classList.add("open");var fw=focus.querySelector(".focus-world");fw.style.backgroundImage='url("'+art[w.id]+'")';fw.className="focus-world fx-"+w.id;focus.querySelector("h2").textContent=w.label;focus.querySelector("p").textContent=short[w.id];var ring=focus.querySelector(".tarot-ring");ring.innerHTML="";w.tarotCandidates.forEach(function(name,i){var b=document.createElement("button");b.className="tarot-card";b.style.setProperty("--i",i);b.innerHTML="<i>"+(glyph[name]||"✦")+"</i><b>"+name+"</b><small>"+w.label+"</small>";b.onclick=function(e){e.stopPropagation();openTarot(name,w)};ring.appendChild(b)})}
function closeFocus(){focus.classList.remove("open");shell.classList.remove("is-focus");selected=null}
document.querySelector(".focus-close").onclick=closeFocus;document.querySelector(".back").onclick=function(){location.href="/"};
document.querySelector(".enter-world").onclick=function(){if(!selected)return;focus.classList.remove("open");flat.classList.add("open");shell.classList.add("is-flat");flat.querySelector("h2").textContent=selected.label;flat.querySelector("p").textContent=selected.summary;var a=flat.querySelector(".flatmap-art");a.style.backgroundImage='url("'+art[selected.id]+'")';var s=flat.querySelector(".flat-symbols");s.innerHTML="";selected.tarotCandidates.forEach(function(name,i){var b=document.createElement("button");b.className="symbol-node";b.style.left=(18+(i%3)*32)+"%";b.style.top=(30+Math.floor(i/3)*42)+"%";b.innerHTML="<i>"+(glyph[name]||"✦")+"</i><span>"+name+"</span>";b.onclick=function(){openTarot(name,selected)};s.appendChild(b)})};
document.querySelector(".flat-close").onclick=function(){flat.classList.remove("open");shell.classList.remove("is-flat","is-focus");selected=null};
function openTarot(name,w){reader.querySelector("h3").textContent=name;reader.querySelector("p").textContent=name+" belongs to Natalie’s provisional "+w.label+" constellation. In the complete corpus build this opens recurrence, source dreams, associations, chronology, territory distribution and interpretation.";reader.classList.add("open")}
document.querySelector(".tarot-close").onclick=function(){reader.classList.remove("open")};
var cv=document.querySelector(".star-canvas"),cx=cv.getContext("2d"),stars=[],mouse={x:0,y:0},dpr=1;
function resize(){dpr=Math.min(devicePixelRatio||1,2);cv.width=innerWidth*dpr;cv.height=innerHeight*dpr;cv.style.width=innerWidth+"px";cv.style.height=innerHeight+"px";cx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(700,Math.max(340,Math.round(innerWidth*innerHeight/3200)))},function(){return{x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.25+Math.random()*1.35,a:.12+Math.random()*.7,p:Math.random()*6.28,z:.2+Math.random()*1.1}})}
addEventListener("resize",resize);resize();addEventListener("pointermove",function(e){mouse.x=(e.clientX/innerWidth-.5)*2;mouse.y=(e.clientY/innerHeight-.5)*2});
function draw(t){cx.clearRect(0,0,innerWidth,innerHeight);stars.forEach(function(s){var q=.72+Math.sin(t*.00055+s.p)*.28;cx.fillStyle="rgba(255,244,224,"+(s.a*q)+")";cx.beginPath();cx.arc(s.x+mouse.x*6*s.z,s.y+mouse.y*4*s.z,Math.max(.12,s.r*q),0,6.283);cx.fill()});requestAnimationFrame(draw)}requestAnimationFrame(draw);